# Generated by Django 2.2.1 on 2019-05-12 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='works.Work')),
                ('content_type', models.IntegerField(choices=[(10, 'folder'), (50, 'audio-wav'), (51, 'audio-flac'), (52, 'audio-mp3_192'), (53, 'audio-mp3_256+'), (60, 'picture-png'), (70, 'video')])),
                ('fingerprint', models.BinaryField(max_length=32, unique=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.TextField(editable=False)),
            ],
        ),
    ]
