# Generated by Django 2.2.1 on 2019-05-14 16:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='works.Work')),
                ('type_id', models.IntegerField(choices=[(0, 'none'), (10, 'folder'), (50, 'audio-wav'), (51, 'audio-flac'), (52, 'audio-mp3'), (60, 'picture-png'), (70, 'video-mkv'), (71, 'video-mp4')], default=0)),
                ('fingerprint', models.BinaryField(max_length=32, unique=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
