# Generated by Django 2.2.1 on 2019-05-14 16:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('doc_url', models.CharField(max_length=30)),
                ('note', models.TextField(default='')),
                ('pics_count', models.IntegerField(default=0)),
                ('words_count', models.IntegerField(default=0)),
                ('audio_length', models.IntegerField(default=0)),
                ('finish_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.Project')),
                ('d4_state', models.IntegerField(choices=[(0, 'vanilla'), (-1, 'preprocessing'), (-2, 'waiting'), (2, 'recruiting'), (3, 'processing'), (4, 'done'), (-10, 'resetted')], default=0)),
                ('d5_state', models.IntegerField(choices=[(0, 'vanilla'), (-1, 'preprocessing'), (-2, 'waiting'), (2, 'recruiting'), (3, 'processing'), (4, 'done'), (-10, 'resetted')], default=-2)),
                ('d6_state', models.IntegerField(choices=[(0, 'vanilla'), (-1, 'preprocessing'), (-2, 'waiting'), (2, 'recruiting'), (3, 'processing'), (4, 'done'), (-10, 'resetted')], default=-2)),
                ('d7_state', models.IntegerField(choices=[(0, 'vanilla'), (-1, 'preprocessing'), (-2, 'waiting'), (2, 'recruiting'), (3, 'processing'), (4, 'done'), (-10, 'resetted')], default=-2)),
                ('d4_start', models.DateTimeField(blank=True, null=True)),
                ('d5_start', models.DateTimeField(blank=True, null=True)),
                ('d6_start', models.DateTimeField(blank=True, null=True)),
                ('d7_start', models.DateTimeField(blank=True, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
