# Generated by Django 2.2.1 on 2019-06-27 12:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=40)),
                ('qq', models.CharField(blank=True, max_length=11)),
                ('line', models.CharField(blank=True, max_length=30)),
                ('groups', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=5)),
                ('note', models.TextField(default='')),
                ('cancelled_count', models.IntegerField(default=0)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
