# Generated by Django 2.2.1 on 2019-06-27 12:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commits',
            fields=[
                ('cid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('type_id', models.IntegerField(choices=[(0, 'none'), (10, 'folder'), (50, 'audio-flac'), (60, 'picture-png'), (70, 'video-mkv'), (71, 'video-mp4')])),
                ('fingerprint', models.BinaryField(max_length=32, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file_exist', models.BooleanField(default=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Work')),
            ],
        ),
    ]
