# Generated by Django 2.2.1 on 2019-06-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('wid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('dep', models.IntegerField(choices=[(40, 'writing'), (50, 'reading'), (51, 'reading_eng'), (60, 'painting'), (70, 'post-production')])),
                ('role', models.CharField(max_length=20)),
                ('state', models.IntegerField(choices=[(-2, 'cancelled_f'), (-1, 'cancelled'), (0, 'normal'), (1, 'finished')], default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'ordering': ('timestamp',),
                'unique_together': {('project', 'dep', 'role')},
            },
        ),
    ]
